/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:caf1b2d8-847c-488c-9592-3b8c91003a41",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zanNgg2EA",
    "aws_user_pools_web_client_id": "1u134rt4i0ia92ebnrqq35tuan",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://x3xz3yfdhfbuplpsa62cxg4nbq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3d7q27jysfgdrb7a3a6w3adp5e",
    "aws_user_files_s3_bucket": "takenotesaws43c1a90481d146058afbd1e84ea5277635407-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
